### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by aolko** [CyclopsMC/FluidConverters#8]
wtf? I can't even run the game

[14:38:36] [Client thread/ERROR] [FML]: The following problems were captured during this phase
[14:38:36] [Client thread/ERROR] [FML]: Caught exception from fluidconverters
java.io.FileNotFoundException: minecraft:textures/blocks/MISSING_ICON_BLOCK_545_null.png
at net.minecraft.client.resources.FallbackResourceManager.func_110536_a(SourceFile:51) ~[bqq.class:?]
at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110536_a(SourceFile:55) ~[brg.class:?]
at org.cyclops.fluidconverters.FluidColorAnalyzer$.readIcon(FluidColorAnalyzer.scala:122) ~[FluidColorAnalyzer$.class:?]
at org.cyclops.fluidconverters.FluidColorAnalyzer$.calculateAverageColor(FluidColorAnalyzer.scala:81) ~[FluidColorAnalyzer$.class:?]
at org.cyclops.fluidconverters.FluidColorAnalyzer$.init(FluidColorAnalyzer.scala:26) ~[FluidColorAnalyzer$.class:?]
at org.cyclops.fluidconverters.FluidConverters$.postInit(FluidConverters.scala:59) ~[FluidConverters$.class:?]
at org.cyclops.fluidconverters.FluidConverters.postInit(FluidConverters.scala) ~[FluidConverters.class:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_55]
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_55]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_55]
at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_55]
at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513) ~[forge-1.7.10-10.13.0.1205-universal.jar:?]
at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_55]
at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_55]
at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-16.0.jar:?]
at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-16.0.jar:?]
at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-16.0.jar:?]
at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-16.0.jar:?]
at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-16.0.jar:?]
at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208) ~[forge-1.7.10-10.13.0.1205-universal.jar:?]
at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187) ~[forge-1.7.10-10.13.0.1205-universal.jar:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_55]
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_55]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_55]
at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_55]
at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-16.0.jar:?]
at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-16.0.jar:?]
at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-16.0.jar:?]
at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-16.0.jar:?]
at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-16.0.jar:?]
at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118) [LoadController.class:?]
at cpw.mods.fml.common.Loader.initializeMods(Loader.java:694) [Loader.class:?]
at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:288) [FMLClientHandler.class:?]
at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:541) [bao.class:?]
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867) [bao.class:?]
at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_55]
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_55]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_55]
at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_55]
at net.minecraft.launchwrapper.Launch.launch(Launch.java:134) [launchwrapper-1.9.jar:?]
at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.9.jar:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_55]
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_55]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_55]
at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_55]
at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:286) [NewLaunch.jar:?]
at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:376) [NewLaunch.jar:?]
at org.multimc.EntryPoint.listen(EntryPoint.java:165) [NewLaunch.jar:?]
at org.multimc.EntryPoint.main(EntryPoint.java:54) [NewLaunch.jar:?]
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 9/26/14 2:38 PM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.io.FileNotFoundException: minecraft:textures/blocks/MISSING_ICON_BLOCK_545_null.png
at cpw.mods.fml.common.LoadController.transition(LoadController.java:162)
at cpw.mods.fml.common.Loader.initializeMods(Loader.java:695)
at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:288)
at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:541)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
at net.minecraft.client.main.Main.main(SourceFile:148)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:134)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:286)
at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:376)
at org.multimc.EntryPoint.listen(EntryPoint.java:165)
at org.multimc.EntryPoint.main(EntryPoint.java:54)
Caused by: java.io.FileNotFoundException: minecraft:textures/blocks/MISSING_ICON_BLOCK_545_null.png
at net.minecraft.client.resources.FallbackResourceManager.func_110536_a(SourceFile:51)
at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110536_a(SourceFile:55)
at org.cyclops.fluidconverters.FluidColorAnalyzer$.readIcon(FluidColorAnalyzer.scala:122)
at org.cyclops.fluidconverters.FluidColorAnalyzer$.calculateAverageColor(FluidColorAnalyzer.scala:81)
at org.cyclops.fluidconverters.FluidColorAnalyzer$.init(FluidColorAnalyzer.scala:26)
at org.cyclops.fluidconverters.FluidConverters$.postInit(FluidConverters.scala:59)
at org.cyclops.fluidconverters.FluidConverters.postInit(FluidConverters.scala)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
at com.google.common.eventbus.EventBus.post(EventBus.java:275)
at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
at com.google.common.eventbus.EventBus.post(EventBus.java:275)
at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
at cpw.mods.fml.common.Loader.initializeMods(Loader.java:694)
... 18 more

**Comment by rubensworks** [comment]
Most likely caused by a mod with an invalid fluid icon, will make a fix for this.

**Comment by aolko** [comment]
it seems like #5 all over again

**Comment by rubensworks** [comment]
It similar, but not the same. In this case there is a mod that is simply registering an invalid icon.
Could you send me the full forge log too? So I can see the resource exceptions and your loaded mods.

**Comment by rubensworks** [comment]
I have a new build ready that should fix this issue, could you try it? https://drone.io/github.com/rubensworks/FluidConverters/files

**Comment by rubensworks** [comment]
Assume fixed.

**Comment by aolko** [comment]
Still broken

---- Minecraft Crash Report ----
// Shall we play a game?

Time: 10/8/14 10:10 AM
Description: Initializing game

java.lang.NullPointerException: Initializing game
at org.cyclops.fluidconverters.FluidColorAnalyzer$.calculateAverageColor(FluidColorAnalyzer.scala:84)
at org.cyclops.fluidconverters.FluidColorAnalyzer$.init(FluidColorAnalyzer.scala:27)
at org.cyclops.fluidconverters.FluidConverters$.postInit(FluidConverters.scala:61)
at org.cyclops.fluidconverters.FluidConverters.postInit(FluidConverters.scala)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
at com.google.common.eventbus.EventBus.post(EventBus.java:275)
at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
at com.google.common.eventbus.EventBus.post(EventBus.java:275)
at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
at cpw.mods.fml.common.Loader.initializeMods(Loader.java:694)
at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:288)
at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:541)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
at net.minecraft.client.main.Main.main(SourceFile:148)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:134)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:286)
at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:376)
at org.multimc.EntryPoint.listen(EntryPoint.java:165)
at org.multimc.EntryPoint.main(EntryPoint.java:54)

## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
at org.cyclops.fluidconverters.FluidColorAnalyzer$.calculateAverageColor(FluidColorAnalyzer.scala:84)
at org.cyclops.fluidconverters.FluidColorAnalyzer$.init(FluidColorAnalyzer.scala:27)
at org.cyclops.fluidconverters.FluidConverters$.postInit(FluidConverters.scala:61)
at org.cyclops.fluidconverters.FluidConverters.postInit(FluidConverters.scala)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
at com.google.common.eventbus.EventBus.post(EventBus.java:275)
at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
at com.google.common.eventbus.EventBus.post(EventBus.java:275)
at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
at cpw.mods.fml.common.Loader.initializeMods(Loader.java:694)
at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:288)
at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:541)

-- Initialization --
Details:
Stacktrace:
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
at net.minecraft.client.main.Main.main(SourceFile:148)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:134)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:286)
at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:376)
at org.multimc.EntryPoint.listen(EntryPoint.java:165)
at org.multimc.EntryPoint.main(EntryPoint.java:54)

-- System Details --
Details:
Minecraft Version: 1.7.10
Operating System: Windows 7 (amd64) version 6.1
Java Version: 1.7.0_55, Oracle Corporation
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
Memory: 708078672 bytes (675 MB) / 1344274432 bytes (1282 MB) up to 1908932608 bytes (1820 MB)
Mod Pack: Unknown / None
LiteLoader Mods: 1 loaded mod(s)
- WorldEditWrapper version 1.2.0
  LaunchWrapper: 37 active transformer(s)
- Transformer: logisticspipes.asm.LogisticsPipesClassInjector
- Transformer: cpw.mods.fml.common.asm.transformers.PatchingTransformer
- Transformer: com.mumfrey.liteloader.transformers.event.EventProxyTransformer
- Transformer: com.mumfrey.liteloader.launch.LiteLoaderTransformer
- Transformer: com.mumfrey.liteloader.client.transformers.CrashReportTransformer
- Transformer: cpw.mods.fml.common.asm.transformers.MarkerTransformer
- Transformer: cpw.mods.fml.common.asm.transformers.SideTransformer
- Transformer: cpw.mods.fml.common.asm.transformers.EventSubscriptionTransformer
- Transformer: codechicken.lib.asm.ClassHeirachyManager
- Transformer: codechicken.core.asm.InterfaceDependancyTransformer
- Transformer: codechicken.core.asm.TweakTransformer
- Transformer: codechicken.core.asm.DelegatedTransformer
- Transformer: codechicken.core.asm.DefaultImplementationTransformer
- Transformer: cofh.asm.TransformerCore
- Transformer: cofh.asm.PCCASMTransformer
- Transformer: logisticspipes.asm.LogisticsClassTransformer
- Transformer: codechicken.nei.asm.NEITransformer
- Transformer: com.kingrunes.somnia.asm.SClassTransformer
- Transformer: cpw.mods.fml.common.asm.transformers.DeobfuscationTransformer
- Transformer: cpw.mods.fml.common.asm.transformers.AccessTransformer
- Transformer: net.minecraftforge.transformers.ForgeAccessTransformer
- Transformer: codechicken.core.asm.CodeChickenAccessTransformer
- Transformer: cofh.asm.PCCAccessTransformer
- Transformer: logisticspipes.asm.LogisticsAccessTransformer
- Transformer: cpw.mods.fml.common.asm.transformers.ModAccessTransformer
- Transformer: cpw.mods.fml.common.asm.transformers.TerminalTransformer
- Transformer: com.mumfrey.liteloader.client.transformers.LiteLoaderEventInjectionTransformer
- Transformer: com.mumfrey.liteloader.client.transformers.LiteLoaderCallbackInjectionTransformer
- Transformer: com.mumfrey.liteloader.client.transformers.JoinGamePacketTransformer
- Transformer: com.mumfrey.liteloader.client.transformers.ServerChatPacketTransformer
- Transformer: com.mumfrey.liteloader.client.transformers.LoginSuccessPacketTransformer
- Transformer: com.mumfrey.liteloader.client.transformers.ChatPacketTransformer
- Transformer: com.mumfrey.liteloader.client.transformers.ServerCustomPayloadPacketTransformer
- Transformer: com.mumfrey.worldeditwrapper.asm.InteractionTransformer
- Transformer: com.mumfrey.liteloader.client.transformers.CustomPayloadPacketTransformer
- Transformer: com.mumfrey.liteloader.client.transformers.MinecraftOverlayTransformer
- Transformer: cpw.mods.fml.common.asm.transformers.ModAPITransformer
  JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms1024m -Xmx2048m -XX:PermSize=256m
  AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP v9.05 FML v7.10.25.1205 Minecraft Forge 10.13.0.1205 Optifine OptiFine_1.7.10_HD_U_A4 84 mods loaded, 84 mods active
  mcp{9.05} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
  FML{7.10.25.1205} [Forge Mod Loader](forge-1.7.10-10.13.0.1205-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
  Forge{10.13.0.1205} [Minecraft Forge](forge-1.7.10-10.13.0.1205-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
  CodeChickenCore{1.0.3.26} [CodeChicken Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
  <CoFH ASM>{000} [CoFH ASM Data Initialization](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
  NotEnoughItems{1.0.3.56} [Not Enough Items](NotEnoughItems-1.7.10-1.0.3.56-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
  SomniaCore{1.3.0.15} [SomniaCore](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
  FLabsBF{4.1.1} [Better Furnaces]([1.7.2]Better_Furnaces_V4.1.1.jar.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
  bdlib{1.4.4.22} [BD Lib](bdlib-mc1710-1.4.4.22.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
  BuildCraft|Core{6.0.17} [BuildCraft](buildcraft-6.0.17.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
  BuildCraft|Energy{6.0.17} [BC Energy](buildcraft-6.0.17.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
  eureka{@VERSION@} [Eureka](Eureka-1.7.10-1.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
  bcadditions{1.6.4} [Buildcraft Additions](BuildcraftAdditions-1.7.10-1.6.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
  CarpentersBlocks{3.2.8} [Carpenter's Blocks](Carpenter's Blocks v3.2.8 - MC 1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
  ChestTransporter{1.1.10} [Chest Transporter](ChestTransporter-1.1.10-MC1.7.10.jar.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
  CoFHCore{1.7.10R3.0.0B6} [CoFH Core](CoFHCore-[1.7.10]3.0.0B6-32.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
  customnpcs{1.7.10b} [CustomNpcs](CustomNPCs_1.7.10b %281%29.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
  dynamictanks{1.0} [Dynamic Liquid Tanks 2.1](dynamictanks-1.1.03.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
  EnderIO{1.7.10-2.1.0_beta.32} [Ender IO](EnderIO-1.7.10-2.1.0_beta.32.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
  factorization.notify{1.0} [Factorization Notification System](Factorization-1.7.10-0.8.88.1.jar.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
  factorization{1.7.10-0.8.88.1} [Factorization](Factorization-1.7.10-0.8.88.1.jar.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
  factorization.misc{1.7.10-0.8.88.1} [Factorization Miscellaneous Nonsense](Factorization-1.7.10-0.8.88.1.jar.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
  fluidconverters{1.1.0b} [Fluid Converters](FluidConverters-1.7.10-1.1.0b.jar) Unloaded->Constructed->Pre-initialized->Initialized->Errored
  BuildCraft|Transport{6.0.17} [BC Transport](buildcraft-6.0.17.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
  BuildCraft|Silicon{6.0.17} [BC Silicon](buildcraft-6.0.17.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
  advgenerators{0.9.1.13} [Advanced Generators](generators-mc1710-0.9.1.13.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
  InfernalMobs{1.5.6} [Infernal Mobs](InfernalMobs-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
  LogisticsPipes{0.8.0.58} [Logistics Pipes](logisticspipes-0.8.0.58.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
  MineFactoryReloaded{1.7.10R2.8.0RC3} [MineFactory Reloaded](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
  UniversalElectricity{@MAJOR@.@MINOR@.@REVIS@} [Universal Electricity](universal-electricity-4.0.0.78-core.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
  ResonantEngine{@MAJOR@.@MINOR@.@REVIS@} [Resonant Engine](resonant-engine-2.0.0.110-core.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
  ForgeMultipart{1.1.0.300} [Forge Multipart](ForgeMultipart-1.7.10-1.1.0.300-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
  ResonantInductionCore{@MAJOR@.@MINOR@.@REVIS@} [Resonant Induction](resonant-induction-0.3.4.91-core.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
  ResonantInduction|Archaic{@MAJOR@.@MINOR@.@REVIS@} [Resonant Induction Archaic](resonant-induction-0.3.4.91-core.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
  ResonantInduction|Mechanical{1.0} [Resonant Induction Mechanical](resonant-induction-0.3.4.91-core.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
  ResonantInduction|Electrical{@MAJOR@.@MINOR@.@REVIS@} [Resonant Induction Electrical](resonant-induction-0.3.4.91-core.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
  Mekanism{7.1.0} [Mekanism](Mekanism-1.7.10-7.1.0.92.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
  MekanismGenerators{7.1.0} [MekanismGenerators](MekanismGenerators-1.7.10-7.1.0.92.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
  MekanismTools{7.1.0} [MekanismTools](MekanismTools-1.7.10-7.1.0.92.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
  MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.0RC3} [MFR Compat: Applied Energistics](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
  MineFactoryReloaded|CompatAtum{1.7.10R2.8.0RC2} [MFR Compat: Atum](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
  MineFactoryReloaded|CompatBackTools{1.7.10R2.8.0RC3} [MFR Compat: BackTools](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
  MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.0RC3} [MFR Compat: BuildCraft](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
  MineFactoryReloaded|CompatChococraft{1.7.10R2.8.0RC2} [MFR Compat: Chococraft](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
  MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.0RC2} [MFR Compat: ExtraBiomes](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
  MineFactoryReloaded|CompatForestry{1.7.10R2.8.0RC3} [MFR Compat: Forestry](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
  MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.0RC3} [MFR Compat: ForgeMicroblock](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
  MineFactoryReloaded|CompatIC2{1.7.10R2.8.0RC3} [MFR Compat: IC2](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
  MineFactoryReloaded|CompatMystcraft{1.7.10R2.8.0RC2} [MFR Compat: Mystcraft](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
  MineFactoryReloaded|CompatPams{1.7.10R2.8.0RC2} [MFR Compat: Pam's Mods](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
  ProjRed|Core{4.4.9.49} [ProjectRed](ProjectRed-Base-1.7.10-4.4.9.49.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
  ProjRed|Exploration{4.4.9.49} [ProjectRed-Exploration](ProjectRed-World-1.7.10-4.4.9.49.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
  MineFactoryReloaded|CompatProjRed{1.7.10R2.8.0RC2} [MFR Compat ProjectRed](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
  MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.0RC3} [MFR Compat: Railcraft](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
  MineFactoryReloaded|CompatRP2{1.7.10R2.8.0RC2} [MFR Compat: RP2](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
  MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.0RC2} [MFR Compat: Sufficient Biomes](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
  MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.0RC3} [MFR Compat: Thaumcraft](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
  MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.0RC3} [MFR Compat: Thermal Expansion](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
  MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.0RC3} [MFR Compat: TwilightForest](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
  MineFactoryReloaded|CompatVanilla{1.7.10R2.8.0RC3} [MFR Compat: Vanilla](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
  ObsidianBoat{v1.3.2} [Obsidian Boat](ObsidianBoat-1.7.10-1.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
  PowerConverters{1.7.10-3.0.0.30} [Power Converters](PowerConverters-1.7.10-3.0.0.30.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
  ProjRed|Transmission{4.4.9.49} [ProjectRed-Transmission](ProjectRed-Integration-1.7.10-4.4.9.49.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
  ProjRed|Transportation{4.4.9.49} [ProjectRed-Transportation](ProjectRed-Mechanical_beta-1.7.10-4.4.9.49.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
  ProjRed|Compatibility{4.4.9.49} [ProjectRed-Compatibility](ProjectRed-Compat-1.7.10-4.4.9.49.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
  ProjRed|Integration{4.4.9.49} [ProjectRed-Integration](ProjectRed-Integration-1.7.10-4.4.9.49.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
  ProjRed|Illumination{4.4.9.49} [ProjectRed-Illumination](ProjectRed-Lighting-1.7.10-4.4.9.49.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
  ProjRed|Expansion{4.4.9.49} [ProjectRed-Expansion](ProjectRed-Mechanical_beta-1.7.10-4.4.9.49.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
  RefinedRelocation{1.0.6d} [Refined Relocation](RefinedRelocation-1.7.10-1.0.6d.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
  ReiMinimap{1.7.10} [Rei's Minimap](ReiMinimap-1.7.10-3.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
  ResonantInduction|Atomic{@MAJOR@.@MINOR@.@REVIS@} [Resonant Induction Atomic](resonant-induction-0.3.4.91-core.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
  Roguelike{1.3.5} [Roguelike Dungeons](roguelike-1.7.10-1.3.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
  AS_Ruins{13.8} [Ruins Spawning System](Ruins-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
  simplefluidtanks{1.7.10-1.2.0.4} [Simple Fluid Tanks](simplefluidtanks-1.7.10-1.2.0.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
  SlimevoidLib{2.0.4.6} [Slimevoid Library](SlimevoidLibrary-2.0.4.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
  Somnia{-au} [Somnia](Somnia-1.3.0.15.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
  StorageDrawers{1.1.1} [Storage Drawers](StorageDrawers-1.1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
  AS_UpdateCheck{1.1.6} [AtomicStryker Update Check Mod](UpdateCheckerMod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
  WholeTreeAxe{1.1.8} [Whole Tree Axe](WholeTreeAxe-1.1.8-MC1.7.10.jar.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
  WirelessRedstoneCore{1.8.0.0} [Wireless Redstone](WirelessRedstoneCore-1.8.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
  BuildCraft|Builders{6.0.17} [BC Builders](buildcraft-6.0.17.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
  BuildCraft|Factory{6.0.17} [BC Factory](buildcraft-6.0.17.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
  McMultipart{1.1.0.300} [Minecraft Multipart Plugin](ForgeMultipart-1.7.10-1.1.0.300-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
  ForgeMicroblock{1.1.0.300} [Forge Microblocks](ForgeMultipart-1.7.10-1.1.0.300-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
  Launched Version: 1.7.10
  LWJGL: 2.9.1
  OpenGL: GeForce GTX 550 Ti/PCIe/SSE2 GL version 4.4.0, NVIDIA Corporation
  GL Caps: Using GL 1.3 multitexturing.
  Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
  Anisotropic filtering is supported and maximum anisotropy is 16.
  Shaders are available because OpenGL 2.1 is supported.

Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: []
Current Language: English (US)
Profiler Position: N/A (disabled)
Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
Anisotropic Filtering: Off (1)

**Comment by rubensworks** [comment]
Well this has been a nasty issue, the latest build here should fix this once and for all: https://drone.io/github.com/rubensworks/FluidConverters/files
Can you confirm?

**Comment by aolko** [comment]
it runs
![screen](http://i.imgur.com/L5x6TJ2.png)
but outputs no liquid, what i'm doing wrong?
json:

```
{
    groupId : "waterfuel",
    groupName : "Water to fuel",
    fluidElements : [
        {
            fluidName: "water",
            value: 1.0
        },
        {
            fluidName: "fuel",
            value: 2.0
        }

    ],
    lossRatio : 1.0,
    hasRecipe : true
}
```

it just wont accept liquids

**Comment by rubensworks** [comment]
Your block will accept water and fuel from all sides, but to output to a side you will have to right click with a water or fuel fluid container (for example a fuel bucket) container on that side to enable the output of that fuel (you will notice that the selected fuel becomes visible inside the small hole.)

**Comment by rubensworks** [comment]
This issue seems to be fixed now. If you still can not output fluids, please report it as a new issue. (And thanks again for reporting the first one)
